{{--
Partial: resources/views/profile/_two-factor.blade.php
Included inside _content.blade.php or used standalone.
Displays the Two-Factor Authentication management card.
--}}

@php
    $user = auth()->user();
@endphp

<div class="card border-0 shadow-lg mt-4"
    style="border-radius: 20px; background: linear-gradient(145deg, #ffffff 0%, #f8f9fa 100%);">
    <div class="card-header bg-transparent border-0 pt-4 px-4">
        <div class="d-flex align-items-center">
            <div class="me-3"
                style="width: 50px; height: 50px; background: rgba(220, 38, 38, 0.1); border-radius: 15px; display: flex; align-items: center; justify-content: center;">
                <i class="bi bi-shield-lock-fill text-danger fs-4"></i>
            </div>
            <div>
                <h5 class="fw-bold mb-0" style="color: #1e293b;">Two-Factor Authentication</h5>
                <p class="text-muted small mb-0">Add an extra layer of security to your account</p>
            </div>
            <div class="ms-auto">
                @if($user->two_factor_enabled)
                    <span class="badge px-3 py-2 rounded-pill"
                        style="background: rgba(22, 163, 74, 0.1); color: #16a34a; font-weight: 600;">
                        <i class="bi bi-check-circle-fill me-1"></i> Enabled
                    </span>
                @else
                    <span class="badge px-3 py-2 rounded-pill"
                        style="background: rgba(100, 116, 139, 0.1); color: #64748b; font-weight: 600;">
                        <i class="bi bi-x-circle-fill me-1"></i> Disabled
                    </span>
                @endif
            </div>
        </div>
    </div>

    <div class="card-body p-4">

        @if($user->two_factor_enabled)
            {{-- Currently enabled — show type and disable option --}}
            <div class="p-4 rounded-4 mb-4"
                style="background: rgba(22, 163, 74, 0.05); border: 2px solid rgba(22, 163, 74, 0.15);">
                <div class="d-flex align-items-center">
                    @if($user->two_factor_type === 'totp')
                        <i class="bi bi-phone-fill text-success me-3 fs-4"></i>
                        <div>
                            <strong style="color: #1e293b;">Authenticator App (TOTP)</strong>
                            <p class="text-muted small mb-0">Codes are generated by your authenticator app every 30 seconds.</p>
                        </div>
                    @else
                        <i class="bi bi-envelope-fill text-success me-3 fs-4"></i>
                        <div>
                            <strong style="color: #1e293b;">Email One-Time Password</strong>
                            <p class="text-muted small mb-0">A code is sent to <strong>{{ $user->email }}</strong> when you log
                                in.</p>
                        </div>
                    @endif
                </div>
            </div>

            <div class="d-flex gap-3 flex-wrap">
                <a href="{{ route('profile.two-factor.recovery-codes') }}"
                    class="btn btn-outline-secondary px-4 py-2 rounded-pill" style="border-width: 2px;">
                    <i class="bi bi-key me-2"></i>View Recovery Codes
                </a>

                <button type="button" class="btn btn-outline-danger px-4 py-2 rounded-pill" style="border-width: 2px;"
                    data-bs-toggle="modal" data-bs-target="#disable2faModal">
                    <i class="bi bi-shield-x me-2"></i>Disable 2FA
                </button>
            </div>

        @else
            {{-- Not enabled — show setup options --}}
            <p class="text-muted mb-4">Choose how you'd like to verify your identity each time you sign in.</p>

            <div class="row g-3 mb-4">
                {{-- TOTP Option --}}
                <div class="col-md-6">
                    <div class="p-4 rounded-4 h-100"
                        style="background: linear-gradient(145deg, #f1f5f9, #e9edf2); border: 2px solid transparent; transition: all 0.3s;"
                        onmouseenter="this.style.borderColor='rgba(220,38,38,0.3)'; this.style.background='rgba(220,38,38,0.03)'"
                        onmouseleave="this.style.borderColor='transparent'; this.style.background='linear-gradient(145deg, #f1f5f9, #e9edf2)'">
                        <div class="d-flex align-items-center mb-3">
                            <div style="width: 44px; height: 44px; background: linear-gradient(135deg, #dc2626, #ef4444); border-radius: 12px; display: flex; align-items: center; justify-content: center;"
                                class="me-3">
                                <i class="bi bi-phone text-white fs-5"></i>
                            </div>
                            <div>
                                <strong style="color: #1e293b;">Authenticator App</strong>
                                <span class="badge ms-2 px-2 py-1 rounded-pill"
                                    style="background: rgba(220,38,38,0.1); color: #dc2626; font-size: 0.65rem;">Recommended</span>
                            </div>
                        </div>
                        <p class="text-muted small mb-4">Use Google Authenticator, Authy, or any TOTP app to generate
                            time-based codes.</p>
                        <a href="{{ route('two-factor.totp.setup') }}" class="btn btn-danger w-100 rounded-pill py-2"
                            style="background: linear-gradient(135deg, #dc2626, #ef4444); border: none;">
                            <i class="bi bi-qr-code me-2"></i>Set Up with App
                        </a>
                    </div>
                </div>

                {{-- Email OTP Option --}}
                <div class="col-md-6">
                    <div class="p-4 rounded-4 h-100"
                        style="background: linear-gradient(145deg, #f1f5f9, #e9edf2); border: 2px solid transparent; transition: all 0.3s;"
                        onmouseenter="this.style.borderColor='rgba(220,38,38,0.3)'; this.style.background='rgba(220,38,38,0.03)'"
                        onmouseleave="this.style.borderColor='transparent'; this.style.background='linear-gradient(145deg, #f1f5f9, #e9edf2)'">
                        <div class="d-flex align-items-center mb-3">
                            <div style="width: 44px; height: 44px; background: linear-gradient(135deg, #64748b, #475569); border-radius: 12px; display: flex; align-items: center; justify-content: center;"
                                class="me-3">
                                <i class="bi bi-envelope text-white fs-5"></i>
                            </div>
                            <strong style="color: #1e293b;">Email OTP</strong>
                        </div>
                        <p class="text-muted small mb-4">Receive a one-time code to <strong>{{ $user->email }}</strong> each
                            time you sign in.</p>
                        <form method="POST" action="{{ route('two-factor.email.enable') }}">
                            @csrf
                            <button type="submit" class="btn btn-outline-secondary w-100 rounded-pill py-2"
                                style="border-width: 2px;">
                                <i class="bi bi-envelope-check me-2"></i>Enable Email OTP
                            </button>
                        </form>
                    </div>
                </div>
            </div>
        @endif
    </div>
</div>

{{-- Disable 2FA Modal --}}
@if($user->two_factor_enabled)
    <div class="modal fade" id="disable2faModal" tabindex="-1" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content border-0 shadow-lg" style="border-radius: 20px;">
                <div class="modal-header border-0 pb-0 px-4 pt-4">
                    <div class="d-flex align-items-center">
                        <div class="me-3"
                            style="width: 44px; height: 44px; background: rgba(220,38,38,0.1); border-radius: 12px; display: flex; align-items: center; justify-content: center;">
                            <i class="bi bi-shield-x text-danger fs-5"></i>
                        </div>
                        <div>
                            <h5 class="fw-bold mb-0" style="color: #1e293b;">Disable Two-Factor Authentication</h5>
                            <p class="text-muted small mb-0">Confirm your password to continue</p>
                        </div>
                    </div>
                    <button type="button" class="btn-close ms-auto" data-bs-dismiss="modal"></button>
                </div>
                <form method="POST" action="{{ route('two-factor.disable') }}">
                    @csrf
                    <div class="modal-body px-4 py-4">
                        <div class="alert rounded-4 mb-4"
                            style="background: rgba(245,158,11,0.1); border: 1.5px solid rgba(245,158,11,0.3); color: #92400e;">
                            <i class="bi bi-exclamation-triangle-fill me-2"></i>
                            Disabling 2FA will make your account less secure. You can re-enable it at any time.
                        </div>
                        <div class="input-group">
                            <span class="input-group-text bg-transparent border-end-0 rounded-start-4"
                                style="border-color: #e2e8f0;">
                                <i class="bi bi-lock text-danger"></i>
                            </span>
                            <input type="password" name="password"
                                class="form-control border-start-0 rounded-end-4 @error('password') is-invalid @enderror"
                                placeholder="Enter your current password" required
                                style="padding: 1rem; border-color: #e2e8f0;">
                        </div>
                        @error('password')
                            <div class="invalid-feedback d-block mt-2">
                                <i class="bi bi-exclamation-circle-fill me-1"></i> {{ $message }}
                            </div>
                        @enderror
                    </div>
                    <div class="modal-footer border-0 px-4 pb-4 pt-0 gap-2">
                        <button type="button" class="btn btn-outline-secondary px-4 py-2 rounded-pill"
                            data-bs-dismiss="modal" style="border-width: 2px;">
                            Cancel
                        </button>
                        <button type="submit" class="btn btn-danger px-5 py-2 rounded-pill"
                            style="background: linear-gradient(135deg, #dc2626, #ef4444); border: none;">
                            <i class="bi bi-shield-x me-2"></i>Yes, Disable 2FA
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endif